"""
pytest-bdd step definitions for features/crud.feature.

Tests use Playwright to drive the Angular UI and verify CRUD operations.
These tests are skipped unless --run-ui is passed to pytest.
"""
import json

import pytest
import requests
from pytest_bdd import given, parsers, scenarios, then, when

scenarios("features/crud.feature")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _api_base(flask_server):
    return flask_server


# ---------------------------------------------------------------------------
# Given steps (Background)
# ---------------------------------------------------------------------------


@given("the sample schema with 4 tables")
def _sample_schema(generated_project_path):
    # Project already generated by session fixture
    pass


@given("a running PostgreSQL test database")
def _postgres(postgres_container):
    pass


@given("the generated Flask API is running")
def _flask(flask_server):
    resp = requests.get(f"{flask_server}/api/get_all", timeout=5)
    assert resp.status_code == 200


@given("the Angular UI is running")
def _angular(angular_ui_url, playwright_browser):
    # Both fixtures are session-scoped; this step just confirms they are ready.
    pass


@given(
    parsers.parse('a customer record exists with name "{name}" and email "{email}"'),
    target_fixture="existing_customer",
)
def existing_customer(flask_server, name, email):
    resp = requests.post(
        f"{flask_server}/api/customers/add",
        json={"name": name, "email": email},
        timeout=5,
    )
    assert resp.status_code == 200
    return resp.json()


# ---------------------------------------------------------------------------
# When steps
# ---------------------------------------------------------------------------


@when("I navigate to the home page")
def navigate_home(page, angular_ui_url):
    page.goto(angular_ui_url)
    page.wait_for_selector("[data-testid='entity-list']", timeout=15_000)


@when(parsers.parse('I navigate to the entity detail page for "{entity_name}"'))
def navigate_entity_detail(page, angular_ui_url, entity_name):
    page.goto(f"{angular_ui_url}/entity/{entity_name}")
    page.wait_for_selector("[data-testid='entity-detail-title']", timeout=15_000)


@when(parsers.parse('I click on the "{entity_name}" entity link'))
def click_entity_link(page, entity_name):
    selector = f"[data-testid='entity-link-{entity_name.lower()}']"
    page.click(selector)
    page.wait_for_selector("[data-testid='entity-detail-title']", timeout=10_000)


@when(parsers.parse('I expand the "{operation}" CRUD panel'))
def expand_crud_panel(page, operation):
    selector = f"[data-testid='panel-toggle-{operation}']"
    page.click(selector)
    # Wait for the body to appear (execute button becomes visible)
    page.wait_for_selector(f"[data-testid='execute-btn-{operation}']", timeout=5_000)


@when(parsers.parse("I enter the JSON body '{body}'"))
def enter_json_body(page, body):
    # Find the visible textarea (the last expanded panel's textarea)
    # We use the fact that only one panel is expanded at a time for simplicity
    textarea = page.locator("textarea.field-textarea").last
    textarea.fill(body)


@when(parsers.parse('I click the execute button for "{operation}"'))
def click_execute(page, operation):
    selector = f"[data-testid='execute-btn-{operation}']"
    page.click(selector)
    # Wait for the result or error to appear
    page.wait_for_selector(
        f"[data-testid='result-block-{operation}'], [data-testid='status-error-{operation}']",
        timeout=10_000,
    )


@when(parsers.parse('I enter the ID "{record_id}" for "{operation}"'))
def enter_id(page, record_id, operation):
    selector = f"[data-testid='id-input-{operation}']"
    page.fill(selector, record_id)


# ---------------------------------------------------------------------------
# Then steps
# ---------------------------------------------------------------------------


@then("I should see the entity list page")
def see_entity_list(page):
    assert page.is_visible("[data-testid='entity-list-title']")
    assert page.is_visible("[data-testid='entity-list']")


@then(parsers.parse('"{entity_name}" should appear in the entity list'))
def entity_appears_in_list(page, entity_name):
    selector = f"[data-testid='entity-link-{entity_name.lower()}']"
    assert page.is_visible(selector), f'Entity link for "{entity_name}" not visible'


@then(parsers.parse('I should be on the entity detail page for "{entity_name}"'))
def on_entity_detail(page, entity_name):
    title = page.text_content("[data-testid='entity-detail-title']")
    assert entity_name in title, f'Expected "{entity_name}" in page title, got "{title}"'


@then("I should see 5 CRUD operation panels")
def see_crud_panels(page):
    operations = ["get-all", "get-one", "add", "update", "delete"]
    for op in operations:
        selector = f"[data-testid='panel-toggle-{op}']"
        assert page.is_visible(selector), f"Panel toggle for '{op}' not visible"


@then(parsers.parse('the result for "{operation}" should contain "{expected}"'))
def result_contains(page, operation, expected):
    selector = f"[data-testid='result-pre-{operation}']"
    content = page.text_content(selector)
    assert expected in content, f'Expected "{expected}" in result for {operation}, got: {content}'
